update apidoc
SamVerschueren/gulp-api-doc pull request #3
Opened 2017-02-28 07:02 UTC by huixisheng

update apidoc version

2017-02-28 09:19 UTC, SamVerschueren requested changes

2017-02-28 09:19 UTC, SamVerschueren commented on package.json
> +  "version": "1.1.1",
Do not update the version manually. I do it at release.

2017-02-28 14:57 UTC, huixisheng commented on package.json
> +  "version": "1.1.1",
ok. I revert version update.

2017-03-01 06:51 UTC, merged

2017-03-01 07:38 UTC, SamVerschueren commented
Released as `2.0.0`. Apparently that version of `apidoc` uses ES2015 syntax and thus didn't work on Node 0.10 and 0.12. So I removed support for those versions as well, hence the major version update.

2017-03-01 07:38 UTC, SamVerschueren commented
And thanks for the pr :tada: :)!